

package com.example.simulatingoperationsofanewspaper.DebanjonCEO;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TableView;

    public class ScheduleBoardMeetingsController{

        @FXML
        private ComboBox<?> employeeListComboBox;

        @FXML
        private TableView<?> performanceTableView;

        @FXML
        void backButton(ActionEvent event) {

        }

        @FXML
        void profileButton(ActionEvent event) {

        }

        @FXML
        void selectEmployeeButton(ActionEvent event) {

        }

    }




}

